package com.froggylord.constellation.config;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

public class HerculesConfig extends BaseConfigGroup {

    { enabled = false; }
    @Override public int currentVersion() { return 0; }

    public boolean visitorHelper = true;
    public boolean visitorShoppingList = true;
    public boolean visitorShowInGarden = true;
    public boolean visitorShowInHub = true;
    public boolean visitorShowPrice = true;
    public boolean visitorShowTotalPrice = true;
    public boolean visitorShowInventoryCount = true;
    public boolean visitorShowSackCount = true;
    public boolean visitorShowVisitors = true;
    public boolean visitorTooltip = true;
    public boolean visitorTooltipItemPrices = false;
    public boolean visitorTooltipCopperPrice = true;
    public boolean visitorTooltipGardenExperiencePrice = false;
    public boolean visitorTooltipProfit = true;
    public boolean visitorRewardChat = true;
    public boolean visitorPreventRareRefuse = true;
    public boolean visitorPreventNewRefuse = true;
    public boolean visitorPreventCheapCopperRefuse = false;
    public boolean visitorPreventExpensiveCopperAccept = false;
    public boolean visitorPreventLowLossRefuse = false;
    public boolean visitorPreventHighLossAccept = false;
    public boolean visitorBlockedSlotHighlight = true;
    public boolean visitorOptionOutline = true;
    public boolean visitorAllowHoldBypass = true;
    public int visitorBypassKey = 341;
    public int visitorCoinsPerCopper = 6000;
    public int visitorAcceptableLoss = 150000;
    public int visitorPriceRefreshSeconds = 30;
    public int visitorBlockedColor = 0xB4555555;
    public int visitorGoodOutlineColor = 0xE055FF55;
    public int visitorBadOutlineColor = 0xE0FF5555;
    public List<String> visitorWarnRewards = new ArrayList<>(List.of(
        "OVERGROWN_GRASS", "GREEN_BANDANA", "ENCHANTMENT_DEDICATION_4", "MUSIC_1_RUNE",
        "DCTR_SPACE_HELM", "ENCHANTMENT_CULTIVATING_1", "ENCHANTMENT_REPLENISH_1", "DYE_COPPER",
        "HYPERCHARGE_GARDEN_CHIP", "DYE_WILD_STRAWBERRY", "VISITORS_GRATITUDE", "FARMING_CONTEST_DISPLAY",
        "ASTRONAUT_PERSONALITY", "FAST_FOOD_BARN_SKIN", "JELLY_GREENHOUSE_SKIN"
    ));

    public boolean farmingControlHud = true;
    public boolean farmingShowCrop = true;
    public boolean farmingShowSpeed = true;
    public boolean farmingShowTargetSpeed = true;
    public boolean farmingShowSpeedDifference = true;
    public boolean farmingShowYawPitch = true;
    public boolean farmingShowTargetAngles = true;
    public boolean farmingShowAngleDifference = true;
    public boolean farmingRequireTool = true;
    public boolean farmingShowOutsideGarden = false;
    public boolean farmingIgnoreAngleTimeout = false;
    public int farmingAngleTimeoutSeconds = 5;
    public int farmingYawPrecision = 4;
    public int farmingPitchPrecision = 4;
    public int farmingSpeedTolerance = 3;
    public int farmingAngleToleranceHundredths = 25;

    public boolean farmingRateHud = true;
    public boolean farmingShowInstantBps = true;
    public boolean farmingShowAverageBps = true;
    public boolean farmingShowSessionBlocks = true;
    public boolean farmingShowSessionTime = true;
    public boolean farmingShowCropsPerMinute = true;
    public int farmingResetAfterSeconds = 5;
    public int farmingBpsPrecision = 2;

    public boolean jacobContestHud = true;
    public boolean jacobShowCrop = true;
    public boolean jacobShowCollected = true;
    public boolean jacobShowRate = true;
    public boolean jacobShowElapsed = true;
    public boolean jacobShowProjectedTotal = true;
    public boolean jacobShowOutsideGarden = false;
    public int jacobContestMinutes = 20;

    public boolean pestCore = true;
    public boolean pestSpawnTitle = true;
    public boolean pestSpawnChat = true;
    public boolean pestSpawnSound = true;
    public boolean pestCompactSpawnChat = false;
    public boolean pestFinderHud = true;
    public boolean pestFinderWorld = true;
    public boolean pestFinderBorders = true;
    public boolean pestFinderNames = true;
    public boolean pestFinderThroughWalls = true;
    public boolean pestFinderOnlyWithVacuum = true;
    public boolean pestFinderKeepAfterHeld = true;
    public boolean pestFinderCurrentPlotRed = true;
    public boolean pestNoPestsTitle = false;
    public boolean pestTimerHud = true;
    public boolean pestTimerOnlyWithTool = true;
    public boolean pestTimerShowLastSpawn = true;
    public boolean pestTimerShowCooldown = true;
    public boolean pestTimerShowAverage = true;
    public boolean pestTimerWarning = true;
    public boolean pestTimerWarningTitle = true;
    public boolean pestTimerWarningChat = true;
    public boolean pestTimerWarningSound = true;
    public boolean pestTimerCustomCooldown = false;
    public boolean pestTimerRepeatWarning = false;
    public boolean pestStatsHud = true;
    public boolean pestStatsOnlyInGarden = true;
    public boolean pestStatsShowKills = true;
    public boolean pestStatsShowDrops = true;
    public boolean pestStatsShowProfit = true;
    public boolean pestStatsShowProfitPerHour = true;
    public boolean pestStatsShowSession = true;
    public boolean pestStatsPersistent = true;
    public int pestFinderHoldSeconds = 1;
    public int pestFinderBorderColor = 0x80FFAA00;
    public int pestFinderCurrentColor = 0x90FF3333;
    public int pestFinderLabelColor = 0xFFFF5555;
    public int pestTimerCustomCooldownSeconds = 135;
    public int pestTimerWarningSeconds = 3;
    public int pestTimerAverageTimeoutSeconds = 30;
    public int pestSpawnTitleTicks = 100;
    public int pestMaxCount = 8;
    public String pestSpawnTemplate = "{amount} {pest-word} spawned in {plot}";
    public Map<String, Long> pestLifetimeKills = new HashMap<>();
    public Map<String, Long> pestLifetimeDrops = new HashMap<>();
    public Map<String, Integer> pestPlotNames = new HashMap<>();
    public double pestLifetimeProfit = 0;

    public boolean pestWaypointEnabled = true;
    public boolean pestWaypointHideParticles = false;
    public boolean pestWaypointHideFireworkParticles = true;
    public boolean pestWaypointHideEnchantParticles = true;
    public boolean pestWaypointHidePathParticles = true;
    public boolean pestWaypointBox = true;
    public boolean pestWaypointBeam = true;
    public boolean pestWaypointLine = false;
    public boolean pestWaypointLabel = true;
    public boolean pestWaypointDistance = true;
    public boolean pestWaypointDifferentiatePlotMiddle = true;
    public boolean pestWaypointThroughWalls = true;
    public boolean pestWaypointClearOnArrival = true;
    public int pestWaypointActivationSeconds = 5;
    public int pestWaypointShowSeconds = 15;
    public int pestWaypointStartRange = 5;
    public int pestWaypointParticleGapTenths = 30;
    public int pestWaypointArrivalRange = 8;
    public int pestWaypointRenderRange = 512;
    public int pestWaypointBeamHeight = 12;
    public int pestWaypointBoxSizeTenths = 8;
    public int pestWaypointColor = 0xFFFF5555;
    public int pestWaypointPlotMiddleColor = 0xFFFFFF55;
    public String pestWaypointLabelTemplate = "Pest Guess {distance}";

    public boolean sprayTracker = true;
    public boolean sprayHud = false;
    public boolean sprayShowNotSprayed = true;
    public boolean sprayExpiryNotification = true;
    public boolean sprayNewNotification = false;
    public boolean sprayExpiryChat = true;
    public boolean sprayExpiryTitle = false;
    public boolean sprayExpirySound = false;
    public boolean sprayNotifyWhileAway = true;
    public boolean sprayIncludePlotNames = true;
    public boolean sprayShowType = true;
    public boolean sprayShowTime = true;
    public boolean sprayOnlyCurrentPlot = true;
    public int sprayDurationMinutes = 30;
    public int sprayExpiryWarningSeconds = 0;
    public int sprayTitleTicks = 80;
    public String sprayExpiryTemplate = "{plots} spray expired";
    public String sprayNewTemplate = "Plot {plot} sprayed with {spray} for {time}";
    public Map<String, Long> sprayExpiryTimes = new HashMap<>();
    public Map<String, String> sprayTypes = new HashMap<>();
    public Map<String, Boolean> sprayNotified = new HashMap<>();

    public boolean stereoHarmony = true;
    public boolean stereoDisplay = true;
    public boolean stereoAlwaysShow = false;
    public boolean stereoShowPest = true;
    public boolean stereoShowCrop = true;
    public boolean stereoHideWhenNone = false;
    public boolean stereoReplaceMenuIcons = true;
    public boolean stereoContestHelper = true;
    public boolean stereoChangeNotification = false;
    public boolean stereoChangeChat = true;
    public boolean stereoChangeTitle = false;
    public boolean stereoChangeSound = false;
    public boolean stereoPersistSelection = true;
    public int stereoMatchingColor = 0xA055FF55;
    public int stereoPlayingColor = 0xA0FFFF55;
    public int stereoTitleTicks = 60;
    public String stereoChangeTemplate = "Stereo Harmony: {vinyl} boosts {pest} for {crop}";
    public String stereoActiveVinyl = "";

    public boolean greenhouseHelper = true;
    public boolean greenhouseGrowth = true;
    public boolean greenhouseOnlyWhenReady = false;
    public boolean greenhouseHighlightHarvestable = true;
    public boolean greenhouseHighlightWater = true;
    public boolean greenhouseReadyNotification = true;
    public boolean greenhouseReadyChat = true;
    public boolean greenhouseReadyTitle = false;
    public boolean greenhouseReadySound = true;
    public boolean greenhouseShowOutsideGarden = true;
    public boolean greenhouseNotifyAfterAway = true;
    public boolean greenhouseShowStageLabel = true;
    public int greenhouseWarningSeconds = 0;
    public int greenhouseForgetAfterMinutes = 60;
    public int greenhouseTitleTicks = 80;
    public int greenhouseHarvestableColor = 0xA055FF55;
    public int greenhouseNotReadyColor = 0xA0FF5555;
    public int greenhouseRewardColor = 0xA0FFFF55;
    public int greenhouseWaterColor = 0xA055FF55;
    public String greenhouseReadyTemplate = "Greenhouse growth stage is {time}";
    public long greenhouseNextCycle = 0;
    public boolean greenhouseCycleNotified = true;

    public boolean fortuneHelper = true;
    public boolean fortuneDisplay = true;
    public boolean fortuneCompact = false;
    public boolean fortuneHideMissingWarnings = false;
    public boolean fortuneShowPestBonus = false;
    public boolean fortuneBonusExpireChat = true;
    public boolean fortuneBonusExpireTitle = false;
    public boolean fortuneBonusExpireSound = false;
    public boolean fortuneBonusClickableAction = true;
    public boolean fortuneBonusCallPhillip = false;
    public boolean fortuneShowCrop = true;
    public boolean fortuneShowBreakdown = false;
    public boolean fortuneShowPestReduction = true;
    public boolean fortuneRequireTool = true;
    public boolean fortuneMissingChat = true;
    public boolean fortuneMissingClickableWidget = true;
    public int fortuneUniversalMissingSeconds = 5;
    public int fortuneCropMissingSeconds = 10;
    public int fortuneMissingRepeatSeconds = 20;
    public int fortuneTitleTicks = 60;
    public String fortuneBonusExpireTemplate = "Pest fortune bonus expired";
    public Map<String, Double> fortuneLatestByCrop = new HashMap<>();
    public int fortunePestBonus = 0;
    public long fortunePestBonusExpiry = 0;
    public boolean fortunePestBonusNotified = true;

    public boolean plotMenuHighlighting = true;
    public boolean plotMenuCurrent = true;
    public boolean plotMenuPests = true;
    public boolean plotMenuSprays = true;
    public boolean plotMenuLocked = true;
    public boolean plotMenuPasting = false;
    public boolean plotMenuStatusLetters = true;
    public boolean plotMenuStatusCounts = true;
    public boolean plotMenuTooltipStatus = true;
    public int plotMenuCurrentColor = 0x9055FF55;
    public int plotMenuPestColor = 0x90FF5555;
    public int plotMenuSprayColor = 0x90FFAA00;
    public int plotMenuLockedColor = 0x90555555;
    public int plotMenuPastingColor = 0x90FFFF55;
    public String plotMenuPriority = "current,pests,sprays,locked,pasting";

    public boolean plotIcons = true;
    public boolean plotIconEditorButton = true;
    public boolean plotIconChatFeedback = true;
    public boolean plotIconTooltipHelp = true;
    public boolean plotIconPerProfile = true;
    public Map<String, String> plotIconStacks = new HashMap<>();

    public boolean cropLocationHelper = true;
    public boolean cropLocationAutoLearn = true;
    public boolean cropLocationAutoChat = true;
    public boolean cropLocationPerProfile = true;
    public boolean cropLocationStartBox = true;
    public boolean cropLocationLastBox = true;
    public boolean cropLocationStartBeam = false;
    public boolean cropLocationLastBeam = true;
    public boolean cropLocationLine = false;
    public boolean cropLocationLabels = true;
    public boolean cropLocationDistance = true;
    public boolean cropLocationThroughWalls = true;
    public boolean cropLocationStartThroughWalls = false;
    public int cropLocationStartColor = 0xAAFFFFFF;
    public int cropLocationLastColor = 0xAAFF55FF;
    public int cropLocationRenderRange = 512;
    public int cropLocationLastMinDistance = 10;
    public int cropLocationBeamHeight = 12;
    public int cropLocationBoxSizeTenths = 10;
    public String cropLocationMode = "START";
    public Map<String, String> cropStartLocations = new HashMap<>();
    public Map<String, String> cropLastFarmedLocations = new HashMap<>();

    public boolean mouseSensitivityHelper = true;
    public boolean mouseSensitivityAutoEnable = false;
    public boolean mouseSensitivityHud = true;
    public boolean mouseSensitivityChat = true;
    public boolean mouseSensitivityLockMouse = false;
    public boolean mouseSensitivityLockOnMousemat = true;
    public boolean mouseSensitivityOnlyPlot = true;
    public boolean mouseSensitivityOnGround = true;
    public boolean mouseSensitivityModeKeybind = true;
    public boolean mouseSensitivityModeTool = true;
    public boolean mouseSensitivityModeFishingRod = false;
    public boolean mouseSensitivityModeVacuum = false;
    public boolean mouseSensitivityModeMousemat = false;
    public boolean mouseSensitivityModeSprayonator = false;
    public boolean mouseSensitivityModeSunsGrasp = false;
    public int mouseSensitivityPercent = 10;
    public int mouseSensitivityGroundToleranceHundredths = 13;
    public String mouseSensitivityUnlockOnTeleport = "ALWAYS";

    public boolean gardenCommands = true;
    public boolean gardenCommandHome = true;
    public boolean gardenCommandBarn = true;
    public boolean gardenCommandPlot = true;
    public boolean gardenHomeHotkey = true;
    public boolean gardenSetHomeHotkey = true;
    public boolean gardenBarnHotkey = true;
    public boolean gardenCommandHotkeyFeedback = false;
    public int gardenCommandHotkeyCooldownMillis = 500;

    public boolean cropMilestoneProgress = true;
    public boolean cropMilestoneShowWithoutTool = false;
    public boolean cropMilestoneShowMaxTier = false;
    public boolean cropMilestoneWarnClose = false;
    public boolean cropMilestoneWarningTitle = true;
    public boolean cropMilestoneWarningSound = true;
    public boolean cropMilestoneShowTier = true;
    public boolean cropMilestoneShowProgress = true;
    public boolean cropMilestoneShowPercent = false;
    public boolean cropMilestoneShowTime = true;
    public boolean cropMilestoneShowCropsSecond = false;
    public boolean cropMilestoneShowCropsMinute = true;
    public boolean cropMilestoneShowCropsHour = false;
    public boolean cropMilestoneShowBlocksSecond = true;
    public boolean cropMilestoneInventoryTiers = true;
    public boolean cropMilestoneInventoryAverage = true;
    public boolean cropMilestoneInventoryOverflow = false;
    public boolean cropMilestoneTooltipTotalProgress = true;
    public int cropMilestoneBpsPrecision = 2;
    public int cropMilestoneBpsResetSeconds = 5;
    public int cropMilestoneWarningSeconds = 5;
    public String cropMilestoneRowOrder = "tier,progress,time,cropsminute,bps";
    public Map<String, Long> cropMilestoneCounters = new HashMap<>();
    public Map<String, Integer> cropMilestoneGoals = new HashMap<>();

    public boolean hoeLevelDisplay = true;
    public boolean hoeLevelOverflow = true;
    public boolean hoeLevelMuteSounds = true;
    public boolean hoeLevelShowLevel = true;
    public boolean hoeLevelShowProgress = true;
    public boolean hoeLevelShowPercent = false;
    public boolean hoeLevelShowRemaining = false;
    public boolean hoeLevelShowRate = false;
    public boolean hoeLevelShowEta = false;
    public boolean hoeLevelShowUpgradeRequired = true;
    public boolean hoeLevelWrongCropWarning = true;
    public int hoeLevelRateResetSeconds = 5;
    public Map<String, Integer> hoeOverflowLevels = new HashMap<>();

    public boolean dnaAnalyzerSolver = true;
    public boolean dnaAnalyzerBlockClose = true;
    public boolean dnaAnalyzerBlockWrongClicks = false;
    public boolean dnaAnalyzerWrongClickFeedback = true;
    public boolean dnaAnalyzerHideTooltips = true;
    public boolean dnaAnalyzerDarkenOthers = true;
    public boolean dnaAnalyzerShowOrder = true;
    public boolean dnaAnalyzerHud = true;
    public boolean dnaAnalyzerAllowEndColumns = true;
    public int dnaAnalyzerFirstColor = 0xB055FF55;
    public int dnaAnalyzerSecondColor = 0xB055FFFF;
    public int dnaAnalyzerOtherColor = 0x70000000;

    // ported from SkyHanni (LGPL-3.0-or-later): config/features/garden/laneswitch/FarmingLaneConfig.kt
    public boolean farmingLaneDistanceDisplay = true;
    public boolean farmingLaneNotification = true;
    public boolean farmingLaneNotificationTitle = true;
    public boolean farmingLaneNotificationChat = false;
    public boolean farmingLaneNotificationSound = true;
    public boolean farmingLaneCornerWaypoints = false;
    public boolean farmingLaneCornerThroughWalls = false;
    public boolean farmingLaneMissingWarning = true;
    public boolean farmingLaneShowCrop = false;
    public boolean farmingLaneShowDistance = true;
    public boolean farmingLaneShowTime = true;
    public boolean farmingLaneShowSpeed = false;
    public int farmingLaneSecondsBefore = 5;
    public int farmingLaneSoundPitchHundredths = 100;
    public int farmingLaneSoundRepeatTicks = 20;
    public int farmingLaneDistancePrecision = 1;
    public int farmingLaneStableTicks = 6;
    public int farmingLaneSlowSpeedHundredths = 100;
    public int farmingLaneMissingRepeatSeconds = 30;
    public int farmingLaneDetectionTurnDistance = 2;
    public int farmingLaneCornerColor = 0xFFFFFF55;
    public int farmingLaneDetectionColor = 0xFFFFFFFF;
    public int farmingLaneCornerBeamHeight = 12;
    public String farmingLaneMessage = "&eLane Switch incoming.";
    public String farmingLaneIgnoredCrops = "";
    public Map<String, String> farmingLanes = new HashMap<>();

    public int speedWheat = 93, speedCarrot = 93, speedPotato = 93, speedNetherWart = 93;
    public int speedPumpkin = 155, speedMelon = 155, speedCocoa = 155, speedSugarCane = 328;
    public int speedCactus = 464, speedMushroom = 233, speedSunflower = 328, speedMoonflower = 328, speedWildRose = 328;

    public float yawWheat = 90f, pitchWheat = 0f;
    public float yawCarrot = -90f, pitchCarrot = 2.8f;
    public float yawPotato = -90f, pitchPotato = 2.8f;
    public float yawNetherWart = 90f, pitchNetherWart = 0f;
    public float yawPumpkin = 90f, pitchPumpkin = -58.5f;
    public float yawMelon = 90f, pitchMelon = -58.5f;
    public float yawCocoa = 180f, pitchCocoa = -45f;
    public float yawSugarCane = -135f, pitchSugarCane = 0f;
    public float yawCactus = -90f, pitchCactus = 0f;
    public float yawMushroom = 116.5f, pitchMushroom = 0f;
    public float yawSunflower = 45f, pitchSunflower = 0f;
    public float yawMoonflower = 45f, pitchMoonflower = 0f;
    public float yawWildRose = 45f, pitchWildRose = 0f;
}
